# syntax=docker/dockerfile:1.7
FROM node:22-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat

FROM base AS deps
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --no-fund

FROM base AS builder
ARG NEXT_PUBLIC_API_BASE_URL=/api
ARG NEXT_PUBLIC_WEAVEY_API_URL=
ARG NEXT_PUBLIC_RAG_API_BASE_URL=https://weavecarbon.com/rag
ARG NEXT_PUBLIC_RAG_COLLECTION=
ARG NEXT_PUBLIC_RAG_COLUMNS_TO_ANSWER=chunk
ARG NEXT_PUBLIC_RAG_NUMBER_DOCS_RETRIEVAL=3
ARG NEXT_PUBLIC_RAG_TIMEOUT_MS=30000
ARG NEXT_PUBLIC_MAPBOX_TOKEN=
ARG NEXT_PUBLIC_MAPBOX_GEOCODING_BASE_URL=https://api.mapbox.com/geocoding/v5/mapbox.places
ARG NEXT_PUBLIC_AUTH_DISABLED=0
ARG NEXT_PUBLIC_ACCOUNT_ENDPOINT=
ARG NEXT_PUBLIC_ENFORCE_CLIENT_ROLE_GUARD=
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WEAVEY_API_URL=$NEXT_PUBLIC_WEAVEY_API_URL
ENV NEXT_PUBLIC_RAG_API_BASE_URL=$NEXT_PUBLIC_RAG_API_BASE_URL
ENV NEXT_PUBLIC_RAG_COLLECTION=$NEXT_PUBLIC_RAG_COLLECTION
ENV NEXT_PUBLIC_RAG_COLUMNS_TO_ANSWER=$NEXT_PUBLIC_RAG_COLUMNS_TO_ANSWER
ENV NEXT_PUBLIC_RAG_NUMBER_DOCS_RETRIEVAL=$NEXT_PUBLIC_RAG_NUMBER_DOCS_RETRIEVAL
ENV NEXT_PUBLIC_RAG_TIMEOUT_MS=$NEXT_PUBLIC_RAG_TIMEOUT_MS
ENV NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN
ENV NEXT_PUBLIC_MAPBOX_GEOCODING_BASE_URL=$NEXT_PUBLIC_MAPBOX_GEOCODING_BASE_URL
ENV NEXT_PUBLIC_AUTH_DISABLED=$NEXT_PUBLIC_AUTH_DISABLED
ENV NEXT_PUBLIC_ACCOUNT_ENDPOINT=$NEXT_PUBLIC_ACCOUNT_ENDPOINT
ENV NEXT_PUBLIC_ENFORCE_CLIENT_ROLE_GUARD=$NEXT_PUBLIC_ENFORCE_CLIENT_ROLE_GUARD
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN --mount=type=cache,id=nextjs-weavecarbon,target=/app/.next/cache \
    npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=5 CMD wget -qO- "http://127.0.0.1:${PORT}/" >/dev/null 2>&1 || exit 1
CMD ["node", "server.js"]
